version: "3"

services:
    mariadb:
        image: mariadb:10.1
        restart: "always"
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        networks:
            - lamp

    www:
        depends_on:
            - mariadb
        build: .
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./www:/var/www/html
        networks:
            - lamp 

    phpmyadmin:
        depends_on:
            - mariadb
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test   
            UPLOAD_LIMIT: 32M
        networks:
            - lamp

networks:
    lamp:
        driver: bridge
